### ISSUE TITLE
Request: Please build the latest version

### ISSUE THREAD

**Issue by TheJonstone** [SkyTechBytes/PlayerStatueBuilder#10]
Hi @SkyTechBytes !
This plugin is awesome and I use it myself on my server.
Now I saw that on 07/17/2022 a change was made which was not built as a new release yet.
Therefore the question if a new version could be built soon.

I would be very happy about feedback!

**Comment by SkyTechBytes** [comment]
Built with the latest changes (should be minor): See https://github.com/SkyTechBytes/PlayerStatueBuilder/releases for all releases.
