### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by nguyen1004** [SkyTechBytes/PlayerStatueBuilder#15]
im trying to build with png file but it doesnt work , can you make a tutorial video please

**Comment by SkyTechBytes** [comment]
https://github.com/SkyTechBytes/PlayerStatueBuilder?tab=readme-ov-file#how-to-create-a-statue-with-a-skin-image-directly-from-your-computer has directions.

Your skin png file should be placed in the data folder as follows: "server" should contain your server jar.
![image](https://github.com/SkyTechBytes/PlayerStatueBuilder/assets/36645753/d332ab1b-29e7-40b3-b0cf-5637d3472ce1)

If you are seeing like a blacked-out skin statue and getting your skin from namemc, open up paint, click "save" to save the file again as a png, and then try again. If there is some other problem, paste the error/logs and the result of the statue creation (if any).
