### ISSUE TITLE
Size of statue 

### ISSUE THREAD

**Issue by TomLewis** [SkyTechBytes/PlayerStatueBuilder#17]
Can we please be able to change the size of a statue, they are absolutely enormous and I woke like to be able to scale down to about 1/3 the size.

**Comment by SkyTechBytes** [comment]
Because skins have a specific resolution, one pixel = one block. Scaling and interpolating will be incredibly difficult to implement. I believe world edit has functionality to scale/deform to shrink your statue though.

**Comment by TomLewis** [comment]
I thought about this just after I posted the ticket, and thought of a way to solve it.

When you grab the skin, just resize the skin first and make a smaller version, then you can build 1:1 off that.
