### ISSUE TITLE
[New Idea] Schematic & Admin Get the number of Blocks

### ISSUE THREAD

**Issue by Mat1212fr** [SkyTechBytes/PlayerStatueBuilder#18]
Hey,
I have no issue but I notice that some things could be improved, this plugin is already very good.

- First, find a way to export your statue as a schematic in a folder of the server, or somewhere else.
- Second, as an admin I don't always want to create a statue (I'm playing survival with friends, but I'm OP).
Maybe add an arguments who just send the blocks needed, as when you are not OP.

If this is added, I will be very happy. I wish you all the best despite everything.

**Comment by SkyTechBytes** [comment]
I think you can use world edit to select and export any build as a schematic [tutorial here](https://madelinemiller.dev/blog/use-schematics-worldedit/). I've added a feature where if you specify the word "quote" after your statue command it should print out all material requirements. You can use this in the meantime:  https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.16.1
