### ISSUE TITLE
How to use statues in other plotsquared plots as admin?

### ISSUE THREAD

**Issue by tomasventura13** [SkyTechBytes/PlayerStatueBuilder#19]
So I'm OP on a server and can't make statues in other player's plots. Is there a specific permission I'm lacking?

**Comment by SkyTechBytes** [comment]
I think this is currently the expected behavior of the plugin. At the moment you'll need to add yourself to the plot or modify something with plotsquared for plotsquared to recognize you as being able to build on that particular plot.

**Comment by tomasventura13** [comment]
There should be an extra permission to bypass that no?
