### ISSUE TITLE
[Suggestion] API

### ISSUE THREAD

**Issue by adviis** [SkyTechBytes/PlayerStatueBuilder#5]
Hi! Your plugin is very cool! I want to use your plugin for my minigame (I mainly mean head and head accessories) . So here's the question - could you please add an API that doesn't require use a player parameter? I really care about it.
Have a nice day!

**Comment by SkyTechBytes** [comment]
Yes sure I can look into this

**Comment by SkyTechBytes** [comment]
Added a few API methods in the latest release:
https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.12
Details on usage: 
See [https://github.com/SkyTechBytes/PlayerStatueBuilder/wiki/API](https://github.com/SkyTechBytes/PlayerStatueBuilder/blob/1.12/url) and https://github.com/SkyTechBytes/PlayerStatueBuilder/tree/master/src/com/skytechbytes/api
Hope this helps!
