### ISSUE TITLE
1.19 second layer not being generated on skin statue

### ISSUE THREAD

**Issue by gamerpogmandude** [SkyTechBytes/PlayerStatueBuilder#8]
I tried to make a skin statue, but the second layer of the skin would not generator. It did generate the second layer of skins in 1.18.2. I have tried everything, and am convinced it is a bug. The server is on 1.19.0.

**Comment by SkyTechBytes** [comment]
What is your username? I will try to replicate the issue. Also, make sure your skin is 64x64 pixels if it isn't already.
